export const tips = [
  "Ej: Paisaje hiperrealista de un campo en medio de un hermoso amanecer donde se alcanza a ver una granja...",
  "Ej: Futbolista con camiseta del Real Madrid con el nombre de Messi en la espalda",
  "Ej: Retrato digital de una mujer con cabello largo al viento, estilo fantasía, con ojos brillantes y paisaje mágico al fondo",
  "Ej: Robot futurista explorando una jungla alienígena bajo un cielo violeta lleno de dos lunas",
  "Ej: Café vintage en París visto desde una ventana empañada con gotas de lluvia y luces cálidas reflejadas",
  "Ej: Dragón volando sobre un castillo medieval rodeado de montañas nevadas bajo un cielo estrellado",
  "Ej: Mujer astronauta flotando frente a un agujero de gusano con galaxias reflejadas en su casco",
  "Ej: Coche clásico rojo estacionado en una carretera desierta al atardecer, con sombras largas y colores cálidos",
  "Ej: Ilustración infantil de un bosque encantado con árboles gigantes, setas mágicas y pequeños duendes jugando",
  "Ej: Escena urbana de Nueva York durante la lluvia, con letreros de neón reflejándose en el pavimento mojado",
  "Ej: Personaje de anime con traje espacial, mirando hacia una supernova en el espacio profundo",
  "Ej: Playa tropical desierta al atardecer con palmeras meciéndose suavemente y el mar calmado reflejando los colores del cielo",
  "Ej: Diseño abstracto con formas geométricas y colores vibrantes fusionándose en un patrón hipnótico",
  "Ej: Gato vestido como chef preparando sushi en una cocina pequeña pero bien equipada",
  "Ej: Ciclista bajando una montaña neblinosa por un camino empinado rodeado de pinos y flores silvestres",
  "Ej: Un submarino antiguo navegando por las ruinas sumergidas de una ciudad perdida bajo el océano oscuro",
  "Ej: Arquitectura surrealista, edificios doblándose como si fueran papel en un mundo sin gravedad",
  "Ej: Castillo hecho completamente de cristal bajo una lluvia de estrellas fugaces",
  "Ej: Ciervo mitad máquina mitad animal, corriendo por un bosque con luces bioluminiscentes",
  "Ej: Viaje en globo aerostático sobre un mar de nubes iluminado por la luna llena",
  "Ej: Bicicleta voladora con alas doradas sobre un pueblo mágico cubierto de nieve",
  "Ej: Ciudad futurista construida dentro de un asteroide hueco en el espacio exterior",
  "Ej: Mapamundi antiguo dibujado sobre una mesa de café en una biblioteca misteriosa",
  "Ej: Barco de vapor surcando un río de lava con islas flotantes a los lados",
  "Ej: Árbol milenario con ramas tan altas que llegan al espacio, conectando mundos",
  "Ej: Explorador solitario caminando sobre un puente invisible entre dos montañas",
  "Ej: Jardín de flores luminosas bajo un cielo morado con tres soles en el horizonte",
  "Ej: Isla que aparece solo una vez al año emergiendo del mar con tesoros olvidados",
  "Ej: Cámara de cine retro grabando una escena en un paisaje marciano lleno de vida",
  "Ej: Biblioteca infinita con escaleras que van en todas direcciones, incluso hacia abajo",
  "Ej: Hombre barbudo sentado junto a una fogata en la cima de una montaña nevada al anochecer",
  "Ej: Tren de vapor cruzando un puente de piedra mientras el río abajo forma un arcoíris",
  "Ej: Avión de papel recién lanzado sobrevolando una ciudad hecha de bloques de Lego",
  "Ej: Huracán de arena formando figuras de animales antiguos en un desierto infinito",
  "Ej: Mariposa gigante llevando a un niño dormido en sus alas sobre un bosque encantado",
  "Ej: Templo antiguo escondido en la copa de un árbol inmenso con escaleras colgantes",
  "Ej: Puerta de madera tallada en la raíz de un árbol que conduce a otro mundo",
  "Ej: Festival de faroles chinos en un río subterráneo con peces brillantes debajo",
  "Ej: Astronauta bailando en gravedad cero rodeado de planetas coloridos",
  "Ej: Castillo subterráneo iluminado por hongos fosforescentes y ríos de plata líquida",
  "Ej: Reloj de bolsillo parado, con engranajes suspendidos en el aire en una habitación vacía",
  "Ej: Casa en forma de seta con ventanas redondas y humo saliendo de la parte superior",
  "Ej: Cuevas de cristal sonoro resonando melodías naturales cada vez que sopla el viento",
  "Ej: Pingüino con traje de buzo explorando un naufragio lleno de tesoros antiguos",
  "Ej: Elefante blanco caminando solo por un desierto helado bajo una aurora boreal",
  "Ej: Mercado flotante en canoas sobre un río cubierto de nenúfares gigantes",
  "Ej: Torre Eiffel de noche con miles de luciérnagas girando en espiral alrededor",
  "Ej: Bosque de secuoyas bajo una niebla dorada con sendero serpenteante y misterioso",
  "Ej: Niña dibujando un barco en la arena y viéndolo cobrar vida al tocar el agua",
  "Ej: Río subterráneo con cascadas que caen hacia el cielo en lugar de hacia abajo",
  "Ej: Teatro abandonado con telas de araña doradas y asientos llenos de polvo de estrellas",
  "Ej: Luna llena reflejada en un estanque rodeado de ranas cantoras",
  "Ej: Mapa del tesoro dibujado en la piel de una tortuga gigante que camina lentamente",
  "Ej: Faro solitario en medio del océano bajo una tormenta eléctrica con relámpagos multicolor",
  "Ej: Pueblo costero con casas pintadas de colores pastel y calles adoquinadas mojadas",
  "Ej: Libro abierto levitando en una biblioteca oscura con páginas volando como aves nocturnas",
  "Ej: Lago congelado bajo la luz del amanecer, con figuras danzando en el hielo",
  "Ej: Plaza central con fuente de chocolate derretido y niños riendo alrededor",
  "Ej: Vagabundo tocando acordeón en un puente de piedra bajo la luna creciente",
  "Ej: Castillo de arena monumental construido por un niño en la orilla de un río mágico",
  "Ej: Estación espacial con jardines internos y plantas creciendo en cápsulas transparentes",
  "Ej: Murciélago mecánico con alas de cobre observando una ciudad dormida desde una torre",
  "Ej: Montaña rusa intergaláctica atravesando nebulosas y asteroides plateados",
  "Ej: Tetería en el techo de un edificio alto con vistas a una ciudad nocturna iluminada",
  "Ej: Cactus gigante con flores luminosas en un desierto bajo constelaciones desconocidas",
  "Ej: Globo terráqueo girando lentamente sobre una mesa de madera en una oficina antigua",
  "Ej: Niño persiguiendo una cometa triangular que parece cambiar de color con el viento",
  "Ej: Arrecife de coral con criaturas fluorescentes nadando lentamente en el océano profundo",
  "Ej: Zepelín pasando sobre un viejo tren de vapor en un paisaje de praderas",
  "Ej: Puente de cuerdas sobre un abismo con montañas nevadas a lo lejos y viento silbando",
  "Ej: Motocicleta clásica estacionada bajo un techo de hojas mojadas por la lluvia",
  "Ej: Oso polar caminando sobre un iceberg con auroras bailando detrás de él",
  "Ej: Habitación vacía con una sola ventana por donde entra luz de luna y una brisa fresca",
  "Ej: Feria de artesanía medieval con puestos de armaduras, pociones y mapas antiguos",
  "Ej: Paloma blanca posada en la punta de una antena alta bajo un cielo gris tormentoso",
  "Ej: Calle empedrada en Florencia con luces cálidas, cafés y música italiana de fondo",
  "Ej: Serpiente de fuego enrollada alrededor de un poste mágico en un ritual ancestral",
  "Ej: Sirena durmiendo en una concha gigante bajo el mar con burbujas rosadas ascendiéndola",
  "Ej: Carruaje tirado por caballos blancos en un camino rural bajo un manto de hojas otoñales",
  "Ej: Dinosaurio robotizado caminando por una selva prehistórica bajo una erupción volcánica",
  "Ej: Mural gigante de un dragón cubriendo toda la fachada de un edificio moderno",
  "Ej: Guitarra acústica apoyada contra una pared en una azotea con vista al atardecer",
  "Ej: Caja de música girando despacio sobre sí misma con partículas de luz flotando alrededor",
  "Ej: Máquina del tiempo con engranajes enormes y cables eléctricos conectados a un rayo",
  "Ej: Piscina olímpica al aire libre bajo la lluvia con ondas reflejando el cielo nublado",
  "Ej: Bote de papel navegar por un charco de agua bajo la luz de una farola en la noche",
  "Ej: Juguete antiguo de cuerda caminando solo sobre una repisa polvorienta",
  "Ej: Ventilador de techo moviéndose lentamente en una habitación con cortinas ondeando suavemente",
  "Ej: Sombrero de copa sobre una silla en un salón abandonado lleno de espejos rotos",
  "Ej: Cafetería vintage con máquinas de espresso antiguas y clientes con ropa retro",
  "Ej: Perro pastor alemán correteando por un campo de trigo bajo un cielo azul intenso",
  "Ej: Aves migratorias formando un triángulo perfecto contra un atardecer naranja",
  "Ej: Cascada escondida detrás de una cortina de vegetación en una selva densa",
  "Ej: Luna llena sobre un cementerio antiguo con lápidas cubiertas de musgo y flores silvestres",
  "Ej: Campanario de una iglesia bajo la tormenta con campana sonando solitaria al viento",
  "Ej: Fogata en la playa con gente contando historias mientras las estrellas brillan intensas",
  "Ej: Robots antiguos reparándose mutuamente en una nave espacial abandonada",
  "Ej: Jarrón con flores marchitas sobre una mesa de hospital junto a una ventana con cortinas blancas",
  "Ej: Hoja de papel cayendo lentamente en cámara lenta sobre un escritorio vacío",
  "Ej: Linterna de hierro colgando de un poste en un camino rural rodeado de árboles altos",
  "Ej: Canciller alemán de los años 30 en un retrato borroso sobre el escritorio de un coleccionista",
  "Ej: Peluche de oso guardando una cama de hospital con sábanas celestes y mesita de luz",
  "Ej: Tetera humeante sobre una servilleta bordada en medio de una mesa de madera oscura",
  "Ej: Cinta métrica enrollándose sola mientras muestra exactamente 42 centímetros",
  "Ej: Maleta de cartón atada con cuerdas apoyada contra una columna en una estación de tren",
  "Ej: Esfera de cristal con una mini ciudad en movimiento dentro, girando lentamente",
  "Ej: Carta de amor antigua doblada y sellada con cera rota sobre una chimenea apagada",
  "Ej: Cualquier descripción adicional que quieras agregar aquí también funciona",
];
